const CATALOG = [
  {
    id: 1,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card1.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 2,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card2.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 3,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card3.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 4,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card4.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 5,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card5.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 6,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card6.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 7,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card7.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 8,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card8.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 9,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card9.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 10,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card10.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 11,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card11.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 12,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card12.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 13,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card13.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 14,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card14.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 15,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card15.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 16,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card16.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 17,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card17.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 18,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card18.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 19,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card19.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 20,
    description: "Размер А5 140*198, акварельная бумага низкой плотности",
    category: "sketch",
    photo: "../img/cards/card20.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 21,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card21.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 22,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card22.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 23,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card23.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 24,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card24.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 25,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card25.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 26,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card26.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 27,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card27.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 28,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card28.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 29,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card29.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 30,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card30.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 31,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card31.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 32,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card32.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 33,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card33.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 34,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card34.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 35,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card35.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 36,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card36.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 37,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card37.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 38,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card38.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 39,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card39.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 40,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card40.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 41,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card41.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 42,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card42.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 43,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card43.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 44,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card44.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 45,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card45.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 46,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card46.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 47,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card47.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 48,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card48.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 49,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card49.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 50,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card50.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 51,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card51.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 52,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card52.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 53,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card53.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 54,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card54.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 55,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card55.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 56,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card56.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 57,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card57.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 58,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card58.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 59,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card59.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 60,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card60.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 61,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card61.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 62,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card62.png",
    price: 350 + " " + "RUB",
  },  
  {
    id: 64,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card64.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 65,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card65.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 67,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card67.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 68,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card68.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 69,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card69.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 70,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card70.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 71,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card71.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 72,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card72.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 73,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card73.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 74,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card74.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 75,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card75.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 76,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card76.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 77,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card77.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 78,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card78.png",
    price: 350 + " " + "RUB",
  },
  {
    id: 79,
    description: "image1",
    category: "sketch",
    photo: "../img/cards/card79.png",
    price: 350 + " " + "RUB",
  },

];
export default CATALOG;
